version: '3.8'

services:
  postgres:
    container_name: zealthy-api-postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: zealthy-api
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres